/* AUTO-GENERATED by tools/fetch_images.py — do not edit by hand.
   Photography credits for images in assets/.
   CC BY and CC BY-SA licences legally require this attribution. */
window.PHOTO_CREDITS = [
  {
    "title": "The Bikeriders premiere.jpg",
    "artist": "https://www.flickr.com/photos/drlovell/",
    "license": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:The_Bikeriders_premiere.jpg"
  },
  {
    "title": "Jodie Comer, The Bikeriders premiere.jpg",
    "artist": "https://www.flickr.com/photos/drlovell/",
    "license": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Jodie_Comer,_The_Bikeriders_premiere.jpg"
  },
  {
    "title": "Jodie Comer (cropped).jpeg",
    "artist": "https://www.flickr.com/photos/drlovell/",
    "license": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Jodie_Comer_(cropped).jpeg"
  },
  {
    "title": "Jodie comer 2023 5.jpg",
    "artist": "The Tony Awards",
    "license": "CC BY 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Jodie_comer_2023_5.jpg"
  },
  {
    "title": "Jodie comer 2023 1.jpg",
    "artist": "The Tony Awards",
    "license": "CC BY 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Jodie_comer_2023_1.jpg"
  },
  {
    "title": "Jodie comer 2023 4.jpg",
    "artist": "The Tony Awards",
    "license": "CC BY 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Jodie_comer_2023_4.jpg"
  },
  {
    "title": "Danny Boyle, Jodie Comer et Aaron Taylor-Johnson 2025 1.jpg",
    "artist": "ManoSolo13241324",
    "license": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:Danny_Boyle,_Jodie_Comer_et_Aaron_Taylor-Johnson_2025_1.jpg"
  },
  {
    "title": "Danny Boyle, Jodie Comer et Aaron Taylor-Johnson 2025 2.jpg",
    "artist": "ManoSolo13241324",
    "license": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:Danny_Boyle,_Jodie_Comer_et_Aaron_Taylor-Johnson_2025_2.jpg"
  },
  {
    "title": "Jodie comer 2023 2.jpg",
    "artist": "The Tony Awards",
    "license": "CC BY 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Jodie_comer_2023_2.jpg"
  },
  {
    "title": "Jodie Comer during an interview, August 2021.png",
    "artist": "Lega Nerd",
    "license": "CC BY 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Jodie_Comer_during_an_interview,_August_2021.png"
  },
  {
    "title": "Jodie comer 2023 3.jpg",
    "artist": "The Tony Awards",
    "license": "CC BY 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Jodie_comer_2023_3.jpg"
  }
];
